spring:
  cloud:
    gateway:
      routes:
        - id: 'auth-route'
          uri: 'http://localhost:8081'
          predicates:
            - 'Path=/auth/**'
        - id: 'game-route'
          uri: 'http://localhost:8080'
          predicates:
            - 'Path=/games/**'
          filters: 'AuthenticationFilter'